//! # Trident Generated Types
//!
//! This file is automatically generated by Trident.
//! **DO NOT EDIT THIS FILE MANUALLY**

#![allow(dead_code)]
#![allow(unused_imports)]

use borsh::BorshDeserialize;
use borsh::BorshSerialize;
use trident_fuzz::fuzzing::*;

// ============================================================================
// PROGRAM MODULES
// ============================================================================

// ----------------------------------------------------------------------------
// Program: meridian
// ----------------------------------------------------------------------------
pub mod meridian {
    use super::*;

    // ------------------------------------------------------------------------
    // Program ID
    // ------------------------------------------------------------------------

    /// Returns the program ID for meridian
    pub fn program_id() -> Pubkey {
        pubkey!("6oe2PzNoWyLMrWHqGAj5hirRUX68z35oqBTW9T1E9mWX")
    }

    // ------------------------------------------------------------------------
    // Instructions
    // ------------------------------------------------------------------------

    // ....................................................................
    // Instruction: BurnPair
    // ....................................................................

    /// Main instruction struct for BurnPair
    pub struct BurnPairInstruction {
        pub accounts: BurnPairInstructionAccountMetas,
        pub data: BurnPairInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for BurnPair instruction
    #[derive(Debug, Clone, Default)]
    pub struct BurnPairInstructionAccountMetas {
        pub user: AccountMeta,

        pub config: AccountMeta,

        pub market: AccountMeta,

        pub user_usdc: AccountMeta,

        pub usdc_escrow: AccountMeta,

        pub yes_mint: AccountMeta,

        pub no_mint: AccountMeta,

        pub user_yes: AccountMeta,

        pub user_no: AccountMeta,

        pub mint_authority: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for BurnPair instruction
    #[derive(Debug, Clone)]
    pub struct BurnPairInstructionAccounts {
        pub user: Pubkey,

        pub config: Pubkey,

        pub market: Pubkey,

        pub user_usdc: Pubkey,

        pub usdc_escrow: Pubkey,

        pub yes_mint: Pubkey,

        pub no_mint: Pubkey,

        pub user_yes: Pubkey,

        pub user_no: Pubkey,

        pub mint_authority: Pubkey,
    }

    impl BurnPairInstructionAccounts {
        pub fn new(
            user: Pubkey,

            config: Pubkey,

            market: Pubkey,

            user_usdc: Pubkey,

            usdc_escrow: Pubkey,

            yes_mint: Pubkey,

            no_mint: Pubkey,

            user_yes: Pubkey,

            user_no: Pubkey,

            mint_authority: Pubkey,
        ) -> Self {
            Self {
                user,

                config,

                market,

                user_usdc,

                usdc_escrow,

                yes_mint,

                no_mint,

                user_yes,

                user_no,

                mint_authority,
            }
        }
    }

    /// Instruction data for BurnPair
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct BurnPairInstructionData {
        pub amount: u64,
    }

    impl BurnPairInstructionData {
        pub fn new(amount: u64) -> Self {
            Self { amount }
        }
    }

    /// Implementation for BurnPairInstruction
    impl BurnPairInstruction {
        fn discriminator() -> [u8; 8] {
            [145u8, 2u8, 176u8, 194u8, 32u8, 205u8, 57u8, 214u8]
        }

        pub fn data(data: BurnPairInstructionData) -> Self {
            Self {
                accounts: BurnPairInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: BurnPairInstructionAccounts) -> Self {
            self.accounts.user = AccountMeta::new(accounts.user, true);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.market = AccountMeta::new_readonly(accounts.market, false);

            self.accounts.user_usdc = AccountMeta::new(accounts.user_usdc, false);

            self.accounts.usdc_escrow = AccountMeta::new(accounts.usdc_escrow, false);

            self.accounts.yes_mint = AccountMeta::new(accounts.yes_mint, false);

            self.accounts.no_mint = AccountMeta::new(accounts.no_mint, false);

            self.accounts.user_yes = AccountMeta::new(accounts.user_yes, false);

            self.accounts.user_no = AccountMeta::new(accounts.user_no, false);

            self.accounts.mint_authority =
                AccountMeta::new_readonly(accounts.mint_authority, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.user.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.market.clone());

            metas.push(self.accounts.user_usdc.clone());

            metas.push(self.accounts.usdc_escrow.clone());

            metas.push(self.accounts.yes_mint.clone());

            metas.push(self.accounts.no_mint.clone());

            metas.push(self.accounts.user_yes.clone());

            metas.push(self.accounts.user_no.clone());

            metas.push(self.accounts.mint_authority.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: BuyNo
    // ....................................................................

    /// Main instruction struct for BuyNo
    pub struct BuyNoInstruction {
        pub accounts: BuyNoInstructionAccountMetas,
        pub data: BuyNoInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for BuyNo instruction
    #[derive(Debug, Clone, Default)]
    pub struct BuyNoInstructionAccountMetas {
        pub user: AccountMeta,

        pub config: AccountMeta,

        pub market: AccountMeta,

        pub book: AccountMeta,

        pub usdc_escrow: AccountMeta,

        pub yes_escrow: AccountMeta,

        pub yes_mint: AccountMeta,

        pub no_mint: AccountMeta,

        pub user_usdc: AccountMeta,

        pub user_yes: AccountMeta,

        pub user_no: AccountMeta,

        pub mint_authority: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for BuyNo instruction
    #[derive(Debug, Clone)]
    pub struct BuyNoInstructionAccounts {
        pub user: Pubkey,

        pub config: Pubkey,

        pub market: Pubkey,

        pub book: Pubkey,

        pub usdc_escrow: Pubkey,

        pub yes_escrow: Pubkey,

        pub yes_mint: Pubkey,

        pub no_mint: Pubkey,

        pub user_usdc: Pubkey,

        pub user_yes: Pubkey,

        pub user_no: Pubkey,

        pub mint_authority: Pubkey,
    }

    impl BuyNoInstructionAccounts {
        pub fn new(
            user: Pubkey,

            config: Pubkey,

            market: Pubkey,

            book: Pubkey,

            usdc_escrow: Pubkey,

            yes_escrow: Pubkey,

            yes_mint: Pubkey,

            no_mint: Pubkey,

            user_usdc: Pubkey,

            user_yes: Pubkey,

            user_no: Pubkey,

            mint_authority: Pubkey,
        ) -> Self {
            Self {
                user,

                config,

                market,

                book,

                usdc_escrow,

                yes_escrow,

                yes_mint,

                no_mint,

                user_usdc,

                user_yes,

                user_no,

                mint_authority,
            }
        }
    }

    /// Instruction data for BuyNo
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct BuyNoInstructionData {
        pub args: BuyNoArgs,
    }

    impl BuyNoInstructionData {
        pub fn new(args: BuyNoArgs) -> Self {
            Self { args }
        }
    }

    /// Implementation for BuyNoInstruction
    impl BuyNoInstruction {
        fn discriminator() -> [u8; 8] {
            [89u8, 240u8, 244u8, 16u8, 196u8, 201u8, 190u8, 163u8]
        }

        pub fn data(data: BuyNoInstructionData) -> Self {
            Self {
                accounts: BuyNoInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: BuyNoInstructionAccounts) -> Self {
            self.accounts.user = AccountMeta::new(accounts.user, true);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.market = AccountMeta::new_readonly(accounts.market, false);

            self.accounts.book = AccountMeta::new(accounts.book, false);

            self.accounts.usdc_escrow = AccountMeta::new(accounts.usdc_escrow, false);

            self.accounts.yes_escrow = AccountMeta::new(accounts.yes_escrow, false);

            self.accounts.yes_mint = AccountMeta::new(accounts.yes_mint, false);

            self.accounts.no_mint = AccountMeta::new(accounts.no_mint, false);

            self.accounts.user_usdc = AccountMeta::new(accounts.user_usdc, false);

            self.accounts.user_yes = AccountMeta::new(accounts.user_yes, false);

            self.accounts.user_no = AccountMeta::new(accounts.user_no, false);

            self.accounts.mint_authority =
                AccountMeta::new_readonly(accounts.mint_authority, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.user.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.market.clone());

            metas.push(self.accounts.book.clone());

            metas.push(self.accounts.usdc_escrow.clone());

            metas.push(self.accounts.yes_escrow.clone());

            metas.push(self.accounts.yes_mint.clone());

            metas.push(self.accounts.no_mint.clone());

            metas.push(self.accounts.user_usdc.clone());

            metas.push(self.accounts.user_yes.clone());

            metas.push(self.accounts.user_no.clone());

            metas.push(self.accounts.mint_authority.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: CancelOrder
    // ....................................................................

    /// Main instruction struct for CancelOrder
    pub struct CancelOrderInstruction {
        pub accounts: CancelOrderInstructionAccountMetas,
        pub data: CancelOrderInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for CancelOrder instruction
    #[derive(Debug, Clone, Default)]
    pub struct CancelOrderInstructionAccountMetas {
        pub user: AccountMeta,

        pub config: AccountMeta,

        pub market: AccountMeta,

        pub book: AccountMeta,

        pub usdc_escrow: AccountMeta,

        pub yes_escrow: AccountMeta,

        pub yes_mint: AccountMeta,

        pub user_usdc: AccountMeta,

        pub user_yes: AccountMeta,

        pub mint_authority: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for CancelOrder instruction
    #[derive(Debug, Clone)]
    pub struct CancelOrderInstructionAccounts {
        pub user: Pubkey,

        pub config: Pubkey,

        pub market: Pubkey,

        pub book: Pubkey,

        pub usdc_escrow: Pubkey,

        pub yes_escrow: Pubkey,

        pub yes_mint: Pubkey,

        pub user_usdc: Pubkey,

        pub user_yes: Pubkey,

        pub mint_authority: Pubkey,
    }

    impl CancelOrderInstructionAccounts {
        pub fn new(
            user: Pubkey,

            config: Pubkey,

            market: Pubkey,

            book: Pubkey,

            usdc_escrow: Pubkey,

            yes_escrow: Pubkey,

            yes_mint: Pubkey,

            user_usdc: Pubkey,

            user_yes: Pubkey,

            mint_authority: Pubkey,
        ) -> Self {
            Self {
                user,

                config,

                market,

                book,

                usdc_escrow,

                yes_escrow,

                yes_mint,

                user_usdc,

                user_yes,

                mint_authority,
            }
        }
    }

    /// Instruction data for CancelOrder
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct CancelOrderInstructionData {
        pub args: CancelOrderArgs,
    }

    impl CancelOrderInstructionData {
        pub fn new(args: CancelOrderArgs) -> Self {
            Self { args }
        }
    }

    /// Implementation for CancelOrderInstruction
    impl CancelOrderInstruction {
        fn discriminator() -> [u8; 8] {
            [95u8, 129u8, 237u8, 240u8, 8u8, 49u8, 223u8, 132u8]
        }

        pub fn data(data: CancelOrderInstructionData) -> Self {
            Self {
                accounts: CancelOrderInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: CancelOrderInstructionAccounts) -> Self {
            self.accounts.user = AccountMeta::new(accounts.user, true);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.market = AccountMeta::new_readonly(accounts.market, false);

            self.accounts.book = AccountMeta::new(accounts.book, false);

            self.accounts.usdc_escrow = AccountMeta::new(accounts.usdc_escrow, false);

            self.accounts.yes_escrow = AccountMeta::new(accounts.yes_escrow, false);

            self.accounts.yes_mint = AccountMeta::new_readonly(accounts.yes_mint, false);

            self.accounts.user_usdc = AccountMeta::new(accounts.user_usdc, false);

            self.accounts.user_yes = AccountMeta::new(accounts.user_yes, false);

            self.accounts.mint_authority =
                AccountMeta::new_readonly(accounts.mint_authority, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.user.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.market.clone());

            metas.push(self.accounts.book.clone());

            metas.push(self.accounts.usdc_escrow.clone());

            metas.push(self.accounts.yes_escrow.clone());

            metas.push(self.accounts.yes_mint.clone());

            metas.push(self.accounts.user_usdc.clone());

            metas.push(self.accounts.user_yes.clone());

            metas.push(self.accounts.mint_authority.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: CreateStrikeMarket
    // ....................................................................

    /// Main instruction struct for CreateStrikeMarket
    pub struct CreateStrikeMarketInstruction {
        pub accounts: CreateStrikeMarketInstructionAccountMetas,
        pub data: CreateStrikeMarketInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for CreateStrikeMarket instruction
    #[derive(Debug, Clone, Default)]
    pub struct CreateStrikeMarketInstructionAccountMetas {
        pub admin: AccountMeta,

        pub config: AccountMeta,

        pub market: AccountMeta,

        pub book: AccountMeta,

        pub yes_mint: AccountMeta,

        pub no_mint: AccountMeta,

        pub mint_authority: AccountMeta,

        pub usdc_escrow: AccountMeta,

        pub yes_escrow: AccountMeta,

        pub usdc_mint: AccountMeta,

        pub token_program: AccountMeta,

        pub system_program: AccountMeta,

        pub rent: AccountMeta,
    }

    /// Account pubkeys for CreateStrikeMarket instruction
    #[derive(Debug, Clone)]
    pub struct CreateStrikeMarketInstructionAccounts {
        pub admin: Pubkey,

        pub config: Pubkey,

        pub market: Pubkey,

        pub book: Pubkey,

        pub yes_mint: Pubkey,

        pub no_mint: Pubkey,

        pub mint_authority: Pubkey,

        pub usdc_escrow: Pubkey,

        pub yes_escrow: Pubkey,

        pub usdc_mint: Pubkey,
    }

    impl CreateStrikeMarketInstructionAccounts {
        pub fn new(
            admin: Pubkey,

            config: Pubkey,

            market: Pubkey,

            book: Pubkey,

            yes_mint: Pubkey,

            no_mint: Pubkey,

            mint_authority: Pubkey,

            usdc_escrow: Pubkey,

            yes_escrow: Pubkey,

            usdc_mint: Pubkey,
        ) -> Self {
            Self {
                admin,

                config,

                market,

                book,

                yes_mint,

                no_mint,

                mint_authority,

                usdc_escrow,

                yes_escrow,

                usdc_mint,
            }
        }
    }

    /// Instruction data for CreateStrikeMarket
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct CreateStrikeMarketInstructionData {
        pub args: CreateStrikeMarketArgs,
    }

    impl CreateStrikeMarketInstructionData {
        pub fn new(args: CreateStrikeMarketArgs) -> Self {
            Self { args }
        }
    }

    /// Implementation for CreateStrikeMarketInstruction
    impl CreateStrikeMarketInstruction {
        fn discriminator() -> [u8; 8] {
            [21u8, 162u8, 50u8, 119u8, 68u8, 218u8, 221u8, 35u8]
        }

        pub fn data(data: CreateStrikeMarketInstructionData) -> Self {
            Self {
                accounts: CreateStrikeMarketInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: CreateStrikeMarketInstructionAccounts) -> Self {
            self.accounts.admin = AccountMeta::new(accounts.admin, true);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.market = AccountMeta::new(accounts.market, false);

            self.accounts.book = AccountMeta::new(accounts.book, false);

            self.accounts.yes_mint = AccountMeta::new(accounts.yes_mint, false);

            self.accounts.no_mint = AccountMeta::new(accounts.no_mint, false);

            self.accounts.mint_authority =
                AccountMeta::new_readonly(accounts.mint_authority, false);

            self.accounts.usdc_escrow = AccountMeta::new(accounts.usdc_escrow, false);

            self.accounts.yes_escrow = AccountMeta::new(accounts.yes_escrow, false);

            self.accounts.usdc_mint = AccountMeta::new_readonly(accounts.usdc_mint, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"),
                false,
            );

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self.accounts.rent = AccountMeta::new_readonly(
                pubkey!("SysvarRent111111111111111111111111111111111"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.admin.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.market.clone());

            metas.push(self.accounts.book.clone());

            metas.push(self.accounts.yes_mint.clone());

            metas.push(self.accounts.no_mint.clone());

            metas.push(self.accounts.mint_authority.clone());

            metas.push(self.accounts.usdc_escrow.clone());

            metas.push(self.accounts.yes_escrow.clone());

            metas.push(self.accounts.usdc_mint.clone());

            metas.push(self.accounts.token_program.clone());

            metas.push(self.accounts.system_program.clone());

            metas.push(self.accounts.rent.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: InitializeConfig
    // ....................................................................

    /// Main instruction struct for InitializeConfig
    pub struct InitializeConfigInstruction {
        pub accounts: InitializeConfigInstructionAccountMetas,
        pub data: InitializeConfigInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for InitializeConfig instruction
    #[derive(Debug, Clone, Default)]
    pub struct InitializeConfigInstructionAccountMetas {
        pub payer: AccountMeta,

        pub config: AccountMeta,

        pub usdc_mint: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for InitializeConfig instruction
    #[derive(Debug, Clone)]
    pub struct InitializeConfigInstructionAccounts {
        pub payer: Pubkey,

        pub config: Pubkey,

        pub usdc_mint: Pubkey,
    }

    impl InitializeConfigInstructionAccounts {
        pub fn new(payer: Pubkey, config: Pubkey, usdc_mint: Pubkey) -> Self {
            Self {
                payer,

                config,

                usdc_mint,
            }
        }
    }

    /// Instruction data for InitializeConfig
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct InitializeConfigInstructionData {
        pub fee_authority: Pubkey,
    }

    impl InitializeConfigInstructionData {
        pub fn new(fee_authority: Pubkey) -> Self {
            Self { fee_authority }
        }
    }

    /// Implementation for InitializeConfigInstruction
    impl InitializeConfigInstruction {
        fn discriminator() -> [u8; 8] {
            [208u8, 127u8, 21u8, 1u8, 194u8, 190u8, 196u8, 70u8]
        }

        pub fn data(data: InitializeConfigInstructionData) -> Self {
            Self {
                accounts: InitializeConfigInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: InitializeConfigInstructionAccounts) -> Self {
            self.accounts.payer = AccountMeta::new(accounts.payer, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.usdc_mint = AccountMeta::new_readonly(accounts.usdc_mint, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.payer.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.usdc_mint.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: MintPair
    // ....................................................................

    /// Main instruction struct for MintPair
    pub struct MintPairInstruction {
        pub accounts: MintPairInstructionAccountMetas,
        pub data: MintPairInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for MintPair instruction
    #[derive(Debug, Clone, Default)]
    pub struct MintPairInstructionAccountMetas {
        pub user: AccountMeta,

        pub config: AccountMeta,

        pub market: AccountMeta,

        pub user_usdc: AccountMeta,

        pub usdc_escrow: AccountMeta,

        pub yes_mint: AccountMeta,

        pub no_mint: AccountMeta,

        pub user_yes: AccountMeta,

        pub user_no: AccountMeta,

        pub mint_authority: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for MintPair instruction
    #[derive(Debug, Clone)]
    pub struct MintPairInstructionAccounts {
        pub user: Pubkey,

        pub config: Pubkey,

        pub market: Pubkey,

        pub user_usdc: Pubkey,

        pub usdc_escrow: Pubkey,

        pub yes_mint: Pubkey,

        pub no_mint: Pubkey,

        pub user_yes: Pubkey,

        pub user_no: Pubkey,

        pub mint_authority: Pubkey,
    }

    impl MintPairInstructionAccounts {
        pub fn new(
            user: Pubkey,

            config: Pubkey,

            market: Pubkey,

            user_usdc: Pubkey,

            usdc_escrow: Pubkey,

            yes_mint: Pubkey,

            no_mint: Pubkey,

            user_yes: Pubkey,

            user_no: Pubkey,

            mint_authority: Pubkey,
        ) -> Self {
            Self {
                user,

                config,

                market,

                user_usdc,

                usdc_escrow,

                yes_mint,

                no_mint,

                user_yes,

                user_no,

                mint_authority,
            }
        }
    }

    /// Instruction data for MintPair
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct MintPairInstructionData {
        pub amount: u64,
    }

    impl MintPairInstructionData {
        pub fn new(amount: u64) -> Self {
            Self { amount }
        }
    }

    /// Implementation for MintPairInstruction
    impl MintPairInstruction {
        fn discriminator() -> [u8; 8] {
            [19u8, 149u8, 94u8, 110u8, 181u8, 186u8, 33u8, 107u8]
        }

        pub fn data(data: MintPairInstructionData) -> Self {
            Self {
                accounts: MintPairInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: MintPairInstructionAccounts) -> Self {
            self.accounts.user = AccountMeta::new(accounts.user, true);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.market = AccountMeta::new_readonly(accounts.market, false);

            self.accounts.user_usdc = AccountMeta::new(accounts.user_usdc, false);

            self.accounts.usdc_escrow = AccountMeta::new(accounts.usdc_escrow, false);

            self.accounts.yes_mint = AccountMeta::new(accounts.yes_mint, false);

            self.accounts.no_mint = AccountMeta::new(accounts.no_mint, false);

            self.accounts.user_yes = AccountMeta::new(accounts.user_yes, false);

            self.accounts.user_no = AccountMeta::new(accounts.user_no, false);

            self.accounts.mint_authority =
                AccountMeta::new_readonly(accounts.mint_authority, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.user.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.market.clone());

            metas.push(self.accounts.user_usdc.clone());

            metas.push(self.accounts.usdc_escrow.clone());

            metas.push(self.accounts.yes_mint.clone());

            metas.push(self.accounts.no_mint.clone());

            metas.push(self.accounts.user_yes.clone());

            metas.push(self.accounts.user_no.clone());

            metas.push(self.accounts.mint_authority.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: PlaceLimitOrder
    // ....................................................................

    /// Main instruction struct for PlaceLimitOrder
    pub struct PlaceLimitOrderInstruction {
        pub accounts: PlaceLimitOrderInstructionAccountMetas,
        pub data: PlaceLimitOrderInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for PlaceLimitOrder instruction
    #[derive(Debug, Clone, Default)]
    pub struct PlaceLimitOrderInstructionAccountMetas {
        pub user: AccountMeta,

        pub config: AccountMeta,

        pub market: AccountMeta,

        pub book: AccountMeta,

        pub usdc_escrow: AccountMeta,

        pub yes_escrow: AccountMeta,

        pub yes_mint: AccountMeta,

        pub user_usdc: AccountMeta,

        pub user_yes: AccountMeta,

        pub mint_authority: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for PlaceLimitOrder instruction
    #[derive(Debug, Clone)]
    pub struct PlaceLimitOrderInstructionAccounts {
        pub user: Pubkey,

        pub config: Pubkey,

        pub market: Pubkey,

        pub book: Pubkey,

        pub usdc_escrow: Pubkey,

        pub yes_escrow: Pubkey,

        pub yes_mint: Pubkey,

        pub user_usdc: Pubkey,

        pub user_yes: Pubkey,

        pub mint_authority: Pubkey,
    }

    impl PlaceLimitOrderInstructionAccounts {
        pub fn new(
            user: Pubkey,

            config: Pubkey,

            market: Pubkey,

            book: Pubkey,

            usdc_escrow: Pubkey,

            yes_escrow: Pubkey,

            yes_mint: Pubkey,

            user_usdc: Pubkey,

            user_yes: Pubkey,

            mint_authority: Pubkey,
        ) -> Self {
            Self {
                user,

                config,

                market,

                book,

                usdc_escrow,

                yes_escrow,

                yes_mint,

                user_usdc,

                user_yes,

                mint_authority,
            }
        }
    }

    /// Instruction data for PlaceLimitOrder
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct PlaceLimitOrderInstructionData {
        pub args: PlaceLimitOrderArgs,
    }

    impl PlaceLimitOrderInstructionData {
        pub fn new(args: PlaceLimitOrderArgs) -> Self {
            Self { args }
        }
    }

    /// Implementation for PlaceLimitOrderInstruction
    impl PlaceLimitOrderInstruction {
        fn discriminator() -> [u8; 8] {
            [108u8, 176u8, 33u8, 186u8, 146u8, 229u8, 1u8, 197u8]
        }

        pub fn data(data: PlaceLimitOrderInstructionData) -> Self {
            Self {
                accounts: PlaceLimitOrderInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: PlaceLimitOrderInstructionAccounts) -> Self {
            self.accounts.user = AccountMeta::new(accounts.user, true);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.market = AccountMeta::new_readonly(accounts.market, false);

            self.accounts.book = AccountMeta::new(accounts.book, false);

            self.accounts.usdc_escrow = AccountMeta::new(accounts.usdc_escrow, false);

            self.accounts.yes_escrow = AccountMeta::new(accounts.yes_escrow, false);

            self.accounts.yes_mint = AccountMeta::new_readonly(accounts.yes_mint, false);

            self.accounts.user_usdc = AccountMeta::new(accounts.user_usdc, false);

            self.accounts.user_yes = AccountMeta::new(accounts.user_yes, false);

            self.accounts.mint_authority =
                AccountMeta::new_readonly(accounts.mint_authority, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.user.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.market.clone());

            metas.push(self.accounts.book.clone());

            metas.push(self.accounts.usdc_escrow.clone());

            metas.push(self.accounts.yes_escrow.clone());

            metas.push(self.accounts.yes_mint.clone());

            metas.push(self.accounts.user_usdc.clone());

            metas.push(self.accounts.user_yes.clone());

            metas.push(self.accounts.mint_authority.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: PlaceMarketOrder
    // ....................................................................

    /// Main instruction struct for PlaceMarketOrder
    pub struct PlaceMarketOrderInstruction {
        pub accounts: PlaceMarketOrderInstructionAccountMetas,
        pub data: PlaceMarketOrderInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for PlaceMarketOrder instruction
    #[derive(Debug, Clone, Default)]
    pub struct PlaceMarketOrderInstructionAccountMetas {
        pub user: AccountMeta,

        pub config: AccountMeta,

        pub market: AccountMeta,

        pub book: AccountMeta,

        pub usdc_escrow: AccountMeta,

        pub yes_escrow: AccountMeta,

        pub yes_mint: AccountMeta,

        pub user_usdc: AccountMeta,

        pub user_yes: AccountMeta,

        pub mint_authority: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for PlaceMarketOrder instruction
    #[derive(Debug, Clone)]
    pub struct PlaceMarketOrderInstructionAccounts {
        pub user: Pubkey,

        pub config: Pubkey,

        pub market: Pubkey,

        pub book: Pubkey,

        pub usdc_escrow: Pubkey,

        pub yes_escrow: Pubkey,

        pub yes_mint: Pubkey,

        pub user_usdc: Pubkey,

        pub user_yes: Pubkey,

        pub mint_authority: Pubkey,
    }

    impl PlaceMarketOrderInstructionAccounts {
        pub fn new(
            user: Pubkey,

            config: Pubkey,

            market: Pubkey,

            book: Pubkey,

            usdc_escrow: Pubkey,

            yes_escrow: Pubkey,

            yes_mint: Pubkey,

            user_usdc: Pubkey,

            user_yes: Pubkey,

            mint_authority: Pubkey,
        ) -> Self {
            Self {
                user,

                config,

                market,

                book,

                usdc_escrow,

                yes_escrow,

                yes_mint,

                user_usdc,

                user_yes,

                mint_authority,
            }
        }
    }

    /// Instruction data for PlaceMarketOrder
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct PlaceMarketOrderInstructionData {
        pub args: PlaceMarketOrderArgs,
    }

    impl PlaceMarketOrderInstructionData {
        pub fn new(args: PlaceMarketOrderArgs) -> Self {
            Self { args }
        }
    }

    /// Implementation for PlaceMarketOrderInstruction
    impl PlaceMarketOrderInstruction {
        fn discriminator() -> [u8; 8] {
            [90u8, 118u8, 192u8, 252u8, 192u8, 99u8, 39u8, 145u8]
        }

        pub fn data(data: PlaceMarketOrderInstructionData) -> Self {
            Self {
                accounts: PlaceMarketOrderInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: PlaceMarketOrderInstructionAccounts) -> Self {
            self.accounts.user = AccountMeta::new(accounts.user, true);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.market = AccountMeta::new_readonly(accounts.market, false);

            self.accounts.book = AccountMeta::new(accounts.book, false);

            self.accounts.usdc_escrow = AccountMeta::new(accounts.usdc_escrow, false);

            self.accounts.yes_escrow = AccountMeta::new(accounts.yes_escrow, false);

            self.accounts.yes_mint = AccountMeta::new_readonly(accounts.yes_mint, false);

            self.accounts.user_usdc = AccountMeta::new(accounts.user_usdc, false);

            self.accounts.user_yes = AccountMeta::new(accounts.user_yes, false);

            self.accounts.mint_authority =
                AccountMeta::new_readonly(accounts.mint_authority, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.user.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.market.clone());

            metas.push(self.accounts.book.clone());

            metas.push(self.accounts.usdc_escrow.clone());

            metas.push(self.accounts.yes_escrow.clone());

            metas.push(self.accounts.yes_mint.clone());

            metas.push(self.accounts.user_usdc.clone());

            metas.push(self.accounts.user_yes.clone());

            metas.push(self.accounts.mint_authority.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Redeem
    // ....................................................................

    /// Main instruction struct for Redeem
    pub struct RedeemInstruction {
        pub accounts: RedeemInstructionAccountMetas,
        pub data: RedeemInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Redeem instruction
    #[derive(Debug, Clone, Default)]
    pub struct RedeemInstructionAccountMetas {
        pub user: AccountMeta,

        pub config: AccountMeta,

        pub market: AccountMeta,

        pub winning_mint: AccountMeta,

        pub user_winning: AccountMeta,

        pub user_usdc: AccountMeta,

        pub usdc_escrow: AccountMeta,

        pub mint_authority: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for Redeem instruction
    #[derive(Debug, Clone)]
    pub struct RedeemInstructionAccounts {
        pub user: Pubkey,

        pub config: Pubkey,

        pub market: Pubkey,

        pub winning_mint: Pubkey,

        pub user_winning: Pubkey,

        pub user_usdc: Pubkey,

        pub usdc_escrow: Pubkey,

        pub mint_authority: Pubkey,
    }

    impl RedeemInstructionAccounts {
        pub fn new(
            user: Pubkey,

            config: Pubkey,

            market: Pubkey,

            winning_mint: Pubkey,

            user_winning: Pubkey,

            user_usdc: Pubkey,

            usdc_escrow: Pubkey,

            mint_authority: Pubkey,
        ) -> Self {
            Self {
                user,

                config,

                market,

                winning_mint,

                user_winning,

                user_usdc,

                usdc_escrow,

                mint_authority,
            }
        }
    }

    /// Instruction data for Redeem
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct RedeemInstructionData {
        pub amount: u64,
    }

    impl RedeemInstructionData {
        pub fn new(amount: u64) -> Self {
            Self { amount }
        }
    }

    /// Implementation for RedeemInstruction
    impl RedeemInstruction {
        fn discriminator() -> [u8; 8] {
            [184u8, 12u8, 86u8, 149u8, 70u8, 196u8, 97u8, 225u8]
        }

        pub fn data(data: RedeemInstructionData) -> Self {
            Self {
                accounts: RedeemInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: RedeemInstructionAccounts) -> Self {
            self.accounts.user = AccountMeta::new(accounts.user, true);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.market = AccountMeta::new_readonly(accounts.market, false);

            self.accounts.winning_mint = AccountMeta::new(accounts.winning_mint, false);

            self.accounts.user_winning = AccountMeta::new(accounts.user_winning, false);

            self.accounts.user_usdc = AccountMeta::new(accounts.user_usdc, false);

            self.accounts.usdc_escrow = AccountMeta::new(accounts.usdc_escrow, false);

            self.accounts.mint_authority =
                AccountMeta::new_readonly(accounts.mint_authority, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.user.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.market.clone());

            metas.push(self.accounts.winning_mint.clone());

            metas.push(self.accounts.user_winning.clone());

            metas.push(self.accounts.user_usdc.clone());

            metas.push(self.accounts.usdc_escrow.clone());

            metas.push(self.accounts.mint_authority.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: SellNo
    // ....................................................................

    /// Main instruction struct for SellNo
    pub struct SellNoInstruction {
        pub accounts: SellNoInstructionAccountMetas,
        pub data: SellNoInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for SellNo instruction
    #[derive(Debug, Clone, Default)]
    pub struct SellNoInstructionAccountMetas {
        pub user: AccountMeta,

        pub config: AccountMeta,

        pub market: AccountMeta,

        pub book: AccountMeta,

        pub usdc_escrow: AccountMeta,

        pub yes_escrow: AccountMeta,

        pub yes_mint: AccountMeta,

        pub no_mint: AccountMeta,

        pub user_usdc: AccountMeta,

        pub user_yes: AccountMeta,

        pub user_no: AccountMeta,

        pub mint_authority: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for SellNo instruction
    #[derive(Debug, Clone)]
    pub struct SellNoInstructionAccounts {
        pub user: Pubkey,

        pub config: Pubkey,

        pub market: Pubkey,

        pub book: Pubkey,

        pub usdc_escrow: Pubkey,

        pub yes_escrow: Pubkey,

        pub yes_mint: Pubkey,

        pub no_mint: Pubkey,

        pub user_usdc: Pubkey,

        pub user_yes: Pubkey,

        pub user_no: Pubkey,

        pub mint_authority: Pubkey,
    }

    impl SellNoInstructionAccounts {
        pub fn new(
            user: Pubkey,

            config: Pubkey,

            market: Pubkey,

            book: Pubkey,

            usdc_escrow: Pubkey,

            yes_escrow: Pubkey,

            yes_mint: Pubkey,

            no_mint: Pubkey,

            user_usdc: Pubkey,

            user_yes: Pubkey,

            user_no: Pubkey,

            mint_authority: Pubkey,
        ) -> Self {
            Self {
                user,

                config,

                market,

                book,

                usdc_escrow,

                yes_escrow,

                yes_mint,

                no_mint,

                user_usdc,

                user_yes,

                user_no,

                mint_authority,
            }
        }
    }

    /// Instruction data for SellNo
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct SellNoInstructionData {
        pub args: SellNoArgs,
    }

    impl SellNoInstructionData {
        pub fn new(args: SellNoArgs) -> Self {
            Self { args }
        }
    }

    /// Implementation for SellNoInstruction
    impl SellNoInstruction {
        fn discriminator() -> [u8; 8] {
            [189u8, 194u8, 132u8, 42u8, 80u8, 249u8, 154u8, 103u8]
        }

        pub fn data(data: SellNoInstructionData) -> Self {
            Self {
                accounts: SellNoInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: SellNoInstructionAccounts) -> Self {
            self.accounts.user = AccountMeta::new(accounts.user, true);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.market = AccountMeta::new_readonly(accounts.market, false);

            self.accounts.book = AccountMeta::new(accounts.book, false);

            self.accounts.usdc_escrow = AccountMeta::new(accounts.usdc_escrow, false);

            self.accounts.yes_escrow = AccountMeta::new(accounts.yes_escrow, false);

            self.accounts.yes_mint = AccountMeta::new(accounts.yes_mint, false);

            self.accounts.no_mint = AccountMeta::new(accounts.no_mint, false);

            self.accounts.user_usdc = AccountMeta::new(accounts.user_usdc, false);

            self.accounts.user_yes = AccountMeta::new(accounts.user_yes, false);

            self.accounts.user_no = AccountMeta::new(accounts.user_no, false);

            self.accounts.mint_authority =
                AccountMeta::new_readonly(accounts.mint_authority, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.user.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.market.clone());

            metas.push(self.accounts.book.clone());

            metas.push(self.accounts.usdc_escrow.clone());

            metas.push(self.accounts.yes_escrow.clone());

            metas.push(self.accounts.yes_mint.clone());

            metas.push(self.accounts.no_mint.clone());

            metas.push(self.accounts.user_usdc.clone());

            metas.push(self.accounts.user_yes.clone());

            metas.push(self.accounts.user_no.clone());

            metas.push(self.accounts.mint_authority.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: SettleMarket
    // ....................................................................

    /// Main instruction struct for SettleMarket
    pub struct SettleMarketInstruction {
        pub accounts: SettleMarketInstructionAccountMetas,
        pub data: SettleMarketInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for SettleMarket instruction
    #[derive(Debug, Clone, Default)]
    pub struct SettleMarketInstructionAccountMetas {
        pub caller: AccountMeta,

        pub market: AccountMeta,

        pub price_update: AccountMeta,
    }

    /// Account pubkeys for SettleMarket instruction
    #[derive(Debug, Clone)]
    pub struct SettleMarketInstructionAccounts {
        pub caller: Pubkey,

        pub market: Pubkey,

        pub price_update: Pubkey,
    }

    impl SettleMarketInstructionAccounts {
        pub fn new(caller: Pubkey, market: Pubkey, price_update: Pubkey) -> Self {
            Self {
                caller,

                market,

                price_update,
            }
        }
    }

    /// Instruction data for SettleMarket
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct SettleMarketInstructionData {}

    impl SettleMarketInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for SettleMarketInstruction
    impl SettleMarketInstruction {
        fn discriminator() -> [u8; 8] {
            [193u8, 153u8, 95u8, 216u8, 166u8, 6u8, 144u8, 217u8]
        }

        pub fn data(data: SettleMarketInstructionData) -> Self {
            Self {
                accounts: SettleMarketInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: SettleMarketInstructionAccounts) -> Self {
            self.accounts.caller = AccountMeta::new(accounts.caller, true);

            self.accounts.market = AccountMeta::new(accounts.market, false);

            self.accounts.price_update = AccountMeta::new_readonly(accounts.price_update, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.caller.clone());

            metas.push(self.accounts.market.clone());

            metas.push(self.accounts.price_update.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: SettleSweep
    // ....................................................................

    /// Main instruction struct for SettleSweep
    pub struct SettleSweepInstruction {
        pub accounts: SettleSweepInstructionAccountMetas,
        pub data: SettleSweepInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for SettleSweep instruction
    #[derive(Debug, Clone, Default)]
    pub struct SettleSweepInstructionAccountMetas {
        pub caller: AccountMeta,

        pub config: AccountMeta,

        pub market: AccountMeta,

        pub book: AccountMeta,

        pub usdc_escrow: AccountMeta,

        pub yes_escrow: AccountMeta,

        pub yes_mint: AccountMeta,

        pub mint_authority: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for SettleSweep instruction
    #[derive(Debug, Clone)]
    pub struct SettleSweepInstructionAccounts {
        pub caller: Pubkey,

        pub config: Pubkey,

        pub market: Pubkey,

        pub book: Pubkey,

        pub usdc_escrow: Pubkey,

        pub yes_escrow: Pubkey,

        pub yes_mint: Pubkey,

        pub mint_authority: Pubkey,
    }

    impl SettleSweepInstructionAccounts {
        pub fn new(
            caller: Pubkey,

            config: Pubkey,

            market: Pubkey,

            book: Pubkey,

            usdc_escrow: Pubkey,

            yes_escrow: Pubkey,

            yes_mint: Pubkey,

            mint_authority: Pubkey,
        ) -> Self {
            Self {
                caller,

                config,

                market,

                book,

                usdc_escrow,

                yes_escrow,

                yes_mint,

                mint_authority,
            }
        }
    }

    /// Instruction data for SettleSweep
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct SettleSweepInstructionData {
        pub args: SettleSweepArgs,
    }

    impl SettleSweepInstructionData {
        pub fn new(args: SettleSweepArgs) -> Self {
            Self { args }
        }
    }

    /// Implementation for SettleSweepInstruction
    impl SettleSweepInstruction {
        fn discriminator() -> [u8; 8] {
            [79u8, 194u8, 152u8, 131u8, 151u8, 36u8, 101u8, 95u8]
        }

        pub fn data(data: SettleSweepInstructionData) -> Self {
            Self {
                accounts: SettleSweepInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: SettleSweepInstructionAccounts) -> Self {
            self.accounts.caller = AccountMeta::new(accounts.caller, true);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.market = AccountMeta::new(accounts.market, false);

            self.accounts.book = AccountMeta::new(accounts.book, false);

            self.accounts.usdc_escrow = AccountMeta::new(accounts.usdc_escrow, false);

            self.accounts.yes_escrow = AccountMeta::new(accounts.yes_escrow, false);

            self.accounts.yes_mint = AccountMeta::new_readonly(accounts.yes_mint, false);

            self.accounts.mint_authority =
                AccountMeta::new_readonly(accounts.mint_authority, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.caller.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.market.clone());

            metas.push(self.accounts.book.clone());

            metas.push(self.accounts.usdc_escrow.clone());

            metas.push(self.accounts.yes_escrow.clone());

            metas.push(self.accounts.yes_mint.clone());

            metas.push(self.accounts.mint_authority.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ------------------------------------------------------------------------
    // Composite Accounts
    // ------------------------------------------------------------------------
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

// NOTE: The auto-generated `Book` struct referenced `meridian::matching::book_side::BookSide<32>`,
// which is not accessible from the trident-tests crate (the meridian program crate is not a
// dependency here). We parse the zero-copy Book account by raw bytes inside the fuzz target
// instead of relying on Borsh deserialization. See `test_fuzz.rs::book_resting_state`.

/// Custom struct: BuyNoArgs
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct BuyNoArgs {
    pub amount: u64,

    pub min_yes_sell_price: u64,
}

impl BuyNoArgs {
    pub fn new(amount: u64, min_yes_sell_price: u64) -> Self {
        Self {
            amount,

            min_yes_sell_price,
        }
    }
}

/// Custom struct: CancelOrderArgs
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct CancelOrderArgs {
    pub side: u8,

    pub price: u64,

    pub seq: u64,
}

impl CancelOrderArgs {
    pub fn new(side: u8, price: u64, seq: u64) -> Self {
        Self { side, price, seq }
    }
}

/// Custom struct: Config
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct Config {
    pub bump: u8,

    pub paused: bool,

    pub admin: Pubkey,

    pub fee_authority: Pubkey,

    pub usdc_mint: Pubkey,
}

impl Config {
    pub fn new(
        bump: u8,

        paused: bool,

        admin: Pubkey,

        fee_authority: Pubkey,

        usdc_mint: Pubkey,
    ) -> Self {
        Self {
            bump,

            paused,

            admin,

            fee_authority,

            usdc_mint,
        }
    }
}

/// Custom struct: CreateStrikeMarketArgs
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct CreateStrikeMarketArgs {
    pub ticker: [u8; 8],

    pub strike_price: u64,

    pub expiry_unix: i64,

    pub pyth_feed_id: [u8; 32],
}

impl CreateStrikeMarketArgs {
    pub fn new(
        ticker: [u8; 8],

        strike_price: u64,

        expiry_unix: i64,

        pyth_feed_id: [u8; 32],
    ) -> Self {
        Self {
            ticker,

            strike_price,

            expiry_unix,

            pyth_feed_id,
        }
    }
}

/// Custom struct: Market
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct Market {
    pub bump: u8,

    pub mint_authority_bump: u8,

    pub settled: bool,

    pub ticker: [u8; 8],

    pub strike_price: u64,

    pub expiry_unix: i64,

    pub yes_mint: Pubkey,

    pub no_mint: Pubkey,

    pub sweep_cursor: u32,

    pub outcome: Option<Outcome>,

    pub pyth_feed_id: [u8; 32],
}

impl Market {
    pub fn new(
        bump: u8,

        mint_authority_bump: u8,

        settled: bool,

        ticker: [u8; 8],

        strike_price: u64,

        expiry_unix: i64,

        yes_mint: Pubkey,

        no_mint: Pubkey,

        sweep_cursor: u32,

        outcome: Option<Outcome>,

        pyth_feed_id: [u8; 32],
    ) -> Self {
        Self {
            bump,

            mint_authority_bump,

            settled,

            ticker,

            strike_price,

            expiry_unix,

            yes_mint,

            no_mint,

            sweep_cursor,

            outcome,

            pyth_feed_id,
        }
    }
}

/// Custom enum: Outcome
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub enum Outcome {
    YesWins,

    NoWins,
}

/// Custom struct: PlaceLimitOrderArgs
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct PlaceLimitOrderArgs {
    pub side: u8,

    pub price: u64,

    pub qty: u64,
}

impl PlaceLimitOrderArgs {
    pub fn new(side: u8, price: u64, qty: u64) -> Self {
        Self { side, price, qty }
    }
}

/// Custom struct: PlaceMarketOrderArgs
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct PlaceMarketOrderArgs {
    pub side: u8,

    pub qty: u64,

    pub slippage_bound: u64,
}

impl PlaceMarketOrderArgs {
    pub fn new(side: u8, qty: u64, slippage_bound: u64) -> Self {
        Self {
            side,

            qty,

            slippage_bound,
        }
    }
}

/// Custom struct: PriceFeedMessage
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct PriceFeedMessage {
    pub feed_id: [u8; 32],

    pub price: i64,

    pub conf: u64,

    pub exponent: i32,

    pub publish_time: i64,

    pub prev_publish_time: i64,

    pub ema_price: i64,

    pub ema_conf: u64,
}

impl PriceFeedMessage {
    pub fn new(
        feed_id: [u8; 32],

        price: i64,

        conf: u64,

        exponent: i32,

        publish_time: i64,

        prev_publish_time: i64,

        ema_price: i64,

        ema_conf: u64,
    ) -> Self {
        Self {
            feed_id,

            price,

            conf,

            exponent,

            publish_time,

            prev_publish_time,

            ema_price,

            ema_conf,
        }
    }
}

/// Custom struct: PriceUpdateV2
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct PriceUpdateV2 {
    pub write_authority: Pubkey,

    pub verification_level: VerificationLevel,

    pub price_message: PriceFeedMessage,

    pub posted_slot: u64,
}

impl PriceUpdateV2 {
    pub fn new(
        write_authority: Pubkey,

        verification_level: VerificationLevel,

        price_message: PriceFeedMessage,

        posted_slot: u64,
    ) -> Self {
        Self {
            write_authority,

            verification_level,

            price_message,

            posted_slot,
        }
    }
}

/// Custom struct: SellNoArgs
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct SellNoArgs {
    pub amount: u64,

    pub max_yes_buy_price: u64,
}

impl SellNoArgs {
    pub fn new(amount: u64, max_yes_buy_price: u64) -> Self {
        Self {
            amount,

            max_yes_buy_price,
        }
    }
}

/// Custom struct: SettleSweepArgs
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct SettleSweepArgs {
    pub max_orders: u32,
}

impl SettleSweepArgs {
    pub fn new(max_orders: u32) -> Self {
        Self { max_orders }
    }
}

/// Custom enum: VerificationLevel
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub enum VerificationLevel {
    Partial { num_signatures: u8 },

    Full,
}

// ============================================================================
// END OF GENERATED FILE
// ============================================================================
